export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const REJECT_LOGIN  = 'REJECT_LOGIN';
export const ACCEPT_LOGIN  = 'ACCEPT_LOGIN';

export const SET_PRODUCTS_FILTER = 'SET_PRODUCT_FILTER';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const SET_TOKEN = 'SET_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';
export const SHOW_PRODUCT_VIEW_DIALOG = 'SHOW_PRODUCT_VIEW_DIALOG';
export const HIDE_PRODUCT_VIEW_DIALOG = 'HIDE_PRODUCT_VIEW_DIALOG';
export const SHOW_ADD_PRODUCT_DIALOG = 'SHOW_ADD_PRODUCT_DIALOG';
export const HIDE_ADD_PRODUCT_DIALOG = 'HIDE_ADD_PRODUCT_DIALOG';
export const GET_SPECIFIC_PRODUCT = 'GET_SPECIFIC_PRODUCT';

export const MODIFY_PRODUCT_REQUEST = 'MODIFY_PRODUCT_REQUEST';
export const MODIFY_PRODUCT_SUCCESS = 'MODIFY_PRODUCT_SUCCESS';
export const MODIFY_PRODUCT_FAILURE = 'MODIFY_PRODUCT_FAILURE';
export const SHOW_MODIFY_PRODUCT_DIALOG = 'SHOW_MODIFY_PRODUCT_DIALOG';
export const HIDE_MODIFY_PRODUCT_DIALOG = 'HIDE_MODIFY_PRODUCT_DIALOG';

export const SHOW_DELETE_PRODUCT_DIALOG = 'SHOW_DELETE_PRODUCT_DIALOG';
export const HIDE_DELETE_PRODUCT_DIALOG = 'HIDE_DELETE_PRODUCT_DIALOG';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';