export const ATTEMPT_LOGIN = "ATTEMPT_LOGIN";
export const REJECT_LOGIN  = "REJECT_LOGIN";
export const ACCEPT_LOGIN  = "ACCEPT_LOGIN";

export const SET_PRODUCTS_FILTER = "SET_PRODUCT_FILTER";
export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
export const SET_TOKEN = "SET_TOKEN";
export const DELETE_TOKEN = "DELETE_TOKEN";

export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const CONFIRM_ADD = 'CONFIRM_ADD';
export const REJECT_ADD = 'REJECT_ADD';