export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const REJECT_LOGIN  = 'REJECT_LOGIN';
export const ACCEPT_LOGIN  = 'ACCEPT_LOGIN';

export const ACCEPT_REGISTRATION  = 'ACCEPT_REGISTRATION';
export const REJECT_REGISTRATION  = 'REJECT_REGISTRATION';
export const SHOW_REGISTRATION = 'SHOW_REGISTRATION';
export const HIDE_REGISTRATION = 'HIDE_REGISTRATION';

export const SET_PRODUCTS_FILTER = 'SET_PRODUCT_FILTER';
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const SET_NUM_PRODUCTS = 'SET_NUM_PRODUCTS';
export const SET_TOKEN = 'SET_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR';
export const CUSTOM_SNACKBAR_MESSAGE = 'CUSTOM_SNACKBAR_MESSAGE';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';
export const ADD_PRODUCT_SUCCESS_SNACKBAR = 'ADD_PRODUCT_SUCCESS_SNACKBAR';
export const SHOW_ADD_PRODUCT_DIALOG = 'SHOW_ADD_PRODUCT_DIALOG';
export const HIDE_ADD_PRODUCT_DIALOG = 'HIDE_ADD_PRODUCT_DIALOG';

export const SET_PRODUCT = 'SET_PRODUCT';
export const SHOW_PRODUCT_VIEW_DIALOG = 'SHOW_PRODUCT_VIEW_DIALOG';
export const HIDE_PRODUCT_VIEW_DIALOG = 'HIDE_PRODUCT_VIEW_DIALOG';
export const GET_SPECIFIC_PRODUCT = 'GET_SPECIFIC_PRODUCT';

export const MODIFY_PRODUCT_REQUEST = 'MODIFY_PRODUCT_REQUEST';
export const MODIFY_PRODUCT_SUCCESS = 'MODIFY_PRODUCT_SUCCESS';
export const MODIFY_PRODUCT_FAILURE = 'MODIFY_PRODUCT_FAILURE';
export const SHOW_MODIFY_PRODUCT_DIALOG = 'SHOW_MODIFY_PRODUCT_DIALOG';
export const HIDE_MODIFY_PRODUCT_DIALOG = 'HIDE_MODIFY_PRODUCT_DIALOG';
export const MODIFY_PRODUCT_SUCCESS_SNACKBAR = 'MODIFY_PRODUCT_SUCCESS_SNACKBAR';

export const SHOW_DELETE_PRODUCT_DIALOG = 'SHOW_DELETE_PRODUCT_DIALOG';
export const HIDE_DELETE_PRODUCT_DIALOG = 'HIDE_DELETE_PRODUCT_DIALOG';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const SET_PRODUCT_PAGE = 'SET_PRODUCT_PAGE';
export const SET_ROWS_PER_PAGE = 'SET_ROWS_PER_PAGE';

export const GET_INVENTORY_COUNT = 'GET_INVENTORY_COUNT';
export const RECEIVE_INVENTORY_COUNT = 'RECEIVE_INVENTORY_COUNT';
export const ADD_TO_INVENTORY_COUNT = 'ADD_TO_INVENTORY_COUNT';
export const REMOVE_TO_INVENTORY_COUNT = 'REMOVE_TO_INVENTORY_COUNT';

export const GET_HISTORY_OF_PRODUCTS_REQUEST = 'GET_HISTORY_OF_PRODUCTS_REQUEST';
export const GET_HISTORY_OF_PRODUCTS_SUCCESS = 'GET_HISTORY_OF_PRODUCTS_SUCCESS';
export const GET_HISTORY_OF_PRODUCTS_FAILURE = 'GET_HISTORY_OF_PRODUCTS_FAILURE';

export const SHOW_REFUND_DIALOG = 'SHOW_REFUND_DIALOG';
export const HIDE_REFUND_DIALOG = 'HIDE_REFUND_DIALOG';

export const FETCH_CART_ITEMS = 'FETCH_CART_ITEMS';
export const RECEIVE_CART_ITEMS = 'RECEIVE_CART_ITEMS';

export const CHECKOUT_CART = "CHECKOUT_CART";
export const RECEIVE_CHECKOUT_CART_RESULT = "RECEIVE_CHECKOUT_CART_RESULT";

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const ADD_TO_CART_SUCCESS_SNACKBAR = 'ADD_TO_CART_SUCCESS_SNACKBAR';

export const FETCH_CLIENTS = "FETCH_CLIENTS";
export const RECEIVE_CLIENTS = "RECEIVE_CLIENTS";

export const SET_USER_TYPE = "SET_USER_TYPE";
export const DELETE_USER_TYPE = "DELETE_USER_TYPE";

export const RESET_FILTERS = "RESET_FILTERS";
export const SET_PRICE_SORT = "SET_PRICE_SORT";

export const GET_BRANDS = "GET_BRANDS";
export const GET_BRANDS_FAILURE = "GET_BRANDS_FAILURE";

export const SHOW_DELETE_CART_ITEM = "SHOW_DELETE_CART_ITEM";
export const HIDE_DELETE_CART_ITEM = "HIDE_DELETE_CART_ITEM";
